server:
  port: 0

greeting:
  message: Welcome, micro UserService

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.microuserservice: DEBUG

token:
  secret: YW5qZmtyaGR5c29ya3JsZGlyZ2tla3JoZHlybXJwYW50bXN0aGZsZGxzcmsyM2FrZmVoZGtzZWhsc21zdGhmbGdrd2xha3RwZHlkbHNkaWRrcmdsd2xka3NnZGs=
  expiration:
    time: 86400000

