server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/JungMYEONG-jin/cloud-config.git
