server:
  port: 8888

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: config-service
  profiles:
    active:
      - native
  cloud:
    config:
      label: main
      server:
        native:
          search-locations:
            - file://${user.home}/Desktop/cert/config
        git:
          uri: https://github.com/JungMYEONG-jin/cloud-config.git
